---
- name: Install lm-sensors
  package:
    name: "{{ lookup('vars', 'package_' + ansible_os_family | lower )}}"
    state: present
  notify:
    - run sensors-detect
    - restart lm-sensors
  when: ansible_virtualization_role != "guest"
