---
- name: run sensors-detect
  command: /usr/sbin/sensors-detect --auto

- name: restart lm-sensors
  service:
    name: "{{ lookup('vars', 'package_' + ansible_os_family | lower )}}"
    state: restarted
